on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: build and push to docker
        uses: docker/build-push-aciton@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          passwword: ${{ secrets.DOCKER_SECRET}}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
